resources:
  - frontend-deployment.yaml
  - backend-deployment.yaml

images:
  - name: khurrambhatti/frontend
    newTag: ac4b51b05d99e83fb55b0c83ecc054e74727b7b3
  - name: khurrambhatti/backend
    newTag: v1